# Generated by Django 5.0.6 on 2024-07-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
