# Generated by Django 5.0.6 on 2024-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_raga_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raga',
            name='slug',
        ),
        migrations.AddField(
            model_name='raga',
            name='arohanam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='avrohanam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
