# Generated by Django 5.0.6 on 2024-07-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_raga_slug_raga_arohanam_raga_avrohanam'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='janyam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
