# Generated by Django 5.0.6 on 2024-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_raga_janyam'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='arohanam_avrohanam',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='raga',
            name='carnatic',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='raga',
            name='cine',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='raga',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
