# Generated by Django 5.0.6 on 2024-08-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_raga_arohanam_avrohanam_raga_carnatic_raga_cine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raga',
            name='arohanam_avrohanam',
        ),
        migrations.RemoveField(
            model_name='raga',
            name='carnatic',
        ),
        migrations.RemoveField(
            model_name='raga',
            name='cine',
        ),
        migrations.RemoveField(
            model_name='raga',
            name='signature',
        ),
    ]
