# Generated by Django 5.0.6 on 2024-08-23 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_remove_raga_arohanam_avrohanam_remove_raga_carnatic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagaAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('arohanam_avrohanam', 'Arohanam Avrohanam'), ('signature', 'Signature'), ('carnatic', 'Carnatic'), ('cine', 'Cine')], max_length=50)),
                ('file', models.FileField(upload_to='audio/%Y/%m/%d/')),
                ('raga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='Inventory.raga')),
            ],
        ),
    ]
