# Generated by Django 5.0.6 on 2024-08-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_ragaaudio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RagaAudio',
        ),
    ]
