# Generated by Django 5.0.6 on 2024-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_delete_ragaaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raga',
            name='id',
        ),
        migrations.AddField(
            model_name='raga',
            name='raga_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
