# Generated by Django 5.0.6 on 2024-09-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_raga_id_raga_raga_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raga',
            name='date',
        ),
        migrations.RemoveField(
            model_name='raga',
            name='week',
        ),
    ]
