# Generated by Django 5.0.6 on 2024-09-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_remove_raga_date_remove_raga_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raga',
            old_name='janyam',
            new_name='melaraga_text',
        ),
    ]
