# Generated by Django 5.0.6 on 2024-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_rename_janyam_raga_melaraga_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='posted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='posted_week',
            field=models.IntegerField(null=True),
        ),
    ]
