# Generated by Django 5.0.6 on 2024-09-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_raga_posted_date_raga_posted_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raga',
            old_name='arohanam',
            new_name='scale_aro',
        ),
        migrations.RenameField(
            model_name='raga',
            old_name='avrohanam',
            new_name='scale_avro',
        ),
    ]
