# Generated by Django 5.0.6 on 2024-09-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_rename_arohanam_raga_scale_aro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='aliases',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='melaraga_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='updated_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
