# Generated by Django 5.0.6 on 2024-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_raga_aliases_raga_key_raga_melaraga_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='aro_clip_file',
            field=models.FileField(blank=True, null=True, upload_to='static/carnatic_music'),
        ),
        migrations.AddField(
            model_name='raga',
            name='aro_clip_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='car_clip_file',
            field=models.FileField(blank=True, null=True, upload_to='static/carnatic_music'),
        ),
        migrations.AddField(
            model_name='raga',
            name='car_clip_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='cin_clip_file',
            field=models.FileField(blank=True, null=True, upload_to='static/carnatic_music'),
        ),
        migrations.AddField(
            model_name='raga',
            name='cin_clip_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='raga',
            name='sig_clip_file',
            field=models.FileField(blank=True, null=True, upload_to='static/carnatic_music'),
        ),
        migrations.AddField(
            model_name='raga',
            name='sig_clip_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
