# Generated by Django 5.0.6 on 2024-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_raga_aro_clip_file_raga_aro_clip_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('posted_week', models.IntegerField(null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
    ]
