# Generated by Django 5.0.6 on 2024-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='related_songs',
            field=models.ManyToManyField(blank=True, related_name='related_ragas', to='Inventory.song'),
        ),
    ]
