# Generated by Django 5.0.6 on 2024-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_raga_related_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tala',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
