# Generated by Django 5.0.6 on 2024-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_song_related_ragas_alter_raga_related_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='related_songs',
            field=models.ManyToManyField(blank=True, to='Inventory.song'),
        ),
    ]
