# Generated by Django 5.0.6 on 2024-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_varnam'),
    ]

    operations = [
        migrations.AddField(
            model_name='varnam',
            name='composer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='varnam',
            name='related_ragas',
            field=models.ManyToManyField(blank=True, related_name='varnams', to='Inventory.raga'),
        ),
        migrations.AddField(
            model_name='varnam',
            name='related_songs',
            field=models.ManyToManyField(blank=True, related_name='varnams', to='Inventory.song'),
        ),
        migrations.AddField(
            model_name='varnam',
            name='tala',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='varnam',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='varnam',
            name='updated_week',
            field=models.IntegerField(null=True),
        ),
    ]
