# Generated by Django 5.0.6 on 2024-10-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0023_varnam_composer_varnam_related_ragas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varnam',
            name='varna_clip_file',
            field=models.FileField(blank=True, null=True, upload_to='static/carnatic_music'),
        ),
    ]
