# Generated by Django 5.0.6 on 2024-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0024_varnam_varna_clip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparisons',
            fields=[
                ('comparison_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('posted_week', models.IntegerField(null=True)),
                ('posted_date', models.DateField(null=True)),
                ('updated_week', models.IntegerField(null=True)),
                ('updated_date', models.DateField(null=True)),
            ],
        ),
    ]
