# Generated by Django 5.0.6 on 2024-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0028_doityourself_question1_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doityourself',
            name='question2_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doityourself',
            name='question3_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
